
#include <iostream>

#include "SolutionFramework.h"

using namespace std;

/**
 * @brief Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
 * the sum of the even-valued terms.
 */
void problem_2_solution( void )
{
    const uint32_t STOP_NUM = 4000000U;
    uint32_t sum = 0;
    uint32_t value_a = 1;
    uint32_t value_b = 2;

    while( value_b < STOP_NUM ) {

        if( (value_b % 2) == 0 ) {
            sum += value_b;
        }

        uint32_t next_value = value_a + value_b;
        value_a = value_b;
        value_b = next_value;
    }

    cout << "Sum: " << sum << endl;
}

ADD_SOLUTION( 2, problem_2_solution );
